// extensions/ocrPrescriptionExtension/prescriptionParser.service.js
const { GoogleGenAI } = require('@google/genai');
const logger = require('../../utils/logger');

class PrescriptionParserService {
  async parseToJSON(rawText) {
    logger.info('Prescription Parser: Structuring raw OCR text into Medication JSON schemas');

    if (!rawText || rawText.trim() === '') {
      throw new Error('Provided OCR text is empty.');
    }

    if (rawText === "MOCK_PRESCRIPTION_DATA") {
      return [
        { name: "Simulated Amoxicillin (Demo)", dosage: "500mg", frequency: "Twice daily", instructions: "Generated by Fallback logic." },
        { name: "Simulated Ibuprofen (Demo)", dosage: "400mg", frequency: "As needed", instructions: "Google API hit quota." }
      ];
    }

    if (!process.env.GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY is not configured for parser layer.');
    }

    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

    const prompt = `
    Analyze the following raw clinical prescription text and parse it into a clear JSON Array of objects.
    Each object must represent a single medication and follow this strict schema:
    [
      {
        "name": "string (the generic or main drug name)",
        "dosage": "string (e.g., 5mg, 10ml - if missing, leave empty string)",
        "frequency": "string (map closest to: 'Once daily', 'Twice daily', 'Three times daily', 'Every 4 hours', 'Every 6 hours', 'Weekly', 'As needed' - default to 'Once daily' if completely unknown)",
        "instructions": "string (any extra instructions, take with water, etc. Leave empty if none)"
      }
    ]
    
    Return ONLY the valid JSON Array block and nothing else, without markdown wrappers like \`\`\`json.
    
    RAW PRESCRIPTION TEXT:
    ${rawText}
    `;

    let response;
    let retries = 3;
    while (retries > 0) {
      try {
        response = await ai.models.generateContent({
          model: 'gemini-1.5-flash',
          contents: prompt
        });
        break; // Success
      } catch (err) {
        retries--;
        logger.warn(`Gemini API Error in Parsing: ${err.message}. Retries left: ${retries}`);
        if (retries === 0) {
          logger.warn('Google API Quota reached. Falling back to Simulated Demo Data.');
          return [
             { name: "Fallback Medication (Demo)", dosage: "10mg", frequency: "Once daily", instructions: "API overloaded, displaying demo data." }
          ];
        }
        await new Promise(res => setTimeout(res, 2000)); // 2s delay
      }
    }

    let jsonString = response && response.text ? response.text : '[]';
    // Clean potential markdown blocks
    jsonString = jsonString.replace(/```json/g, '').replace(/```/g, '').trim();

    try {
      const parsed = JSON.parse(jsonString);
      if (!Array.isArray(parsed)) {
         return [parsed]; // Force array
      }
      return parsed;
    } catch (err) {
      logger.error(`Parser logic failed to interpret LLM json output: ${jsonString}`);
      throw new Error('AI output was not valid JSON.');
    }
  }
}

module.exports = new PrescriptionParserService();
